import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:post_in/models/models.dart';
import 'package:post_in/providers/providers.dart';
import 'package:provider/provider.dart';
import 'package:image_picker/image_picker.dart';
import 'dart:io';

part 'functions.dart';
part 'account_button.dart';
part 'post_widget.dart';
part 'input_post.dart';
part 'text_field_decoration.dart';
part 'komentar_widget.dart';
part 'input_komentar.dart';
part 'akun_widget.dart';
// part 'komentar_btn.dart';
part 'ikuti_btn.dart';